# .github/workflows/deploy-frontend.yml
name: Deploy Frontend to VPS

on:
  push:
    branches: [main, master] # Canvia per la teva branca principal
  workflow_dispatch: # Permet executar manualment

env:
  REGISTRY: ghcr.io
  IMAGE_FRONTEND: ghcr.io/ericzapater/orkestra-web

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          build-args: |
            API_URL=${{ secrets.API_URL }}
          tags: |
            ${{ env.IMAGE_FRONTEND }}:latest
            ${{ env.IMAGE_FRONTEND }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy Frontend to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/orkestra

            # Login al registry
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Pull nova imatge del frontend
            docker pull ${{ env.IMAGE_FRONTEND }}:latest

            # Aixecar tot l'stack (Traefik, backend, frontend, etc.)
            docker-compose down
            docker-compose up -d

            # Neteja imatges antigues
            docker image prune -f

            echo "✅ Desplegament completat - Tot l'stack aixecat!"

      - name: Verify deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/orkestra
            docker-compose ps
            echo "🌍 Stack complet disponible a: https://orkestra.zenith.ovh"
